using System;
using System.Collections.Generic;
using System.Text;

namespace intro
{
   public class info
    {

        public int id { set; get; }
       public int type { set; get; }
       public string title{ set; get; }
       public string body { set; get; }

       public info (int _id , int _type , string _title , string _body)
       {
           id = _id ;
           type = _type ;
           title = _title;
           body = _body;

       }
    }






   public class info_fill
   {
       public List<info> q = new List<info>();

       public void fun1()
       {
           q.Add(new info(0, 0, "How do I get hepatitis A ?                  ", "Hepatitis A is spread through close contact with an\ninfected person, or by eating virus A contaminated \nfood or drinking water . Because the virus is found \nin the stool (feces) of infected people , eating food \nprepared by an infected person,who does not wash \nhis/her hands properly afterusing the washroom, is \none way of getting the virus.\n\nEatin graw or undercooked seafood and shellfish\nfrom water polluted with sewage, or eating salad\ngreens that are rinsed in contaminated water are\nother ways of becoming infected.\n\nSharing drug-use equipment, \n\nWhile often considered to be a ‘traveller’s disease’\nhepatitis A can be contracted in Canada. Hepatitis A\noutbreaks or scares in Canada are most often\nassociated with infected food handlers in\nrestaurants and grocery stores or with contaminated\nproduce."));
           q.Add(new info(1, 0, "Who is most at risk of getting hepatitis A ?", "You have an increased risk of hepatitis A if you:\n\n•travel to regions where hepatitis A is common \n\n•live with someone who is newly infected with \nhepatitis A,\n\n•use injection drugs and share contaminated drug\npreparation/injection materials\n\n•are an inmate in jail"));
           q.Add(new info(2, 0, "What are the symptoms of hepatitis A?       ", "Not all people infected with hepatitis A virus will have symptoms. \nPre-school children often have no symptoms, and, in general, \nchildren will have milder symptoms than adults. Symptoms may \noccur 15 to 50 days from the time you first come in contact \nwith the hepatitis A virus.\n\nWhen you first become infected with the hepatitis A virus it is called \nacute infection. Typical symptoms of an acute hepatitis A infection \ninclude: fatigue, nausea and vomiting, abdominal discomfort, jaundice \n(yellowing of the whites of the eyes and skin), dark urine, low grade \nfever and loss of appetite.\n\nThe older you are when you get hepatitis A, the more likely that you \nwill experience more severe symptoms. Some people feel sick for one \nto two weeks, while in others the symptoms may last several months. \nHepatitis A rarely causes death. However, persons with pre-existing \nchronic liver disease, including chronic hepatitis B and C, are at \nincreased risk of serious complications from this infection.\n\n"));


           q.Add(new info(3, 0, "What is hepatitis B?                        ", "Hepatitis B is a type of liver disease caused by the hepatitis B virus \nand is one of the most common strains of viral hepatitis (the others \nare the hepatitis A virus and the hepatitis C virus). Many people who \nbecome infected with hepatitis B never feel sick and recover completely. \nOthers get a brief, acute illness with fatigue and loss of appetite and \ntheir skin and eyes turn yellow (a condition called “jaundice”). Less \nthan 5% of adults who get acute hepatitis B develop chronic hepatitis, \nwhich can lead to cirrhosis (liver scarring) and/or liver cancer later \nin life. Chronic hepatitis B is a “silent” disease because often no \nsymptoms appear until your liver is severely damaged. Infants and \nchildren infected with hepatitis B have a much greater likelihood of \ndeveloping a chronic infection than adults."));
           q.Add(new info(4, 0, "How do I get hepatitis B?                   ", "A person who has acute or chronic hepatitis B can spread the infection \nto other people through his/her blood and other body fluids or by \nsexual contact. The hepatitis B virus is found mainly in the blood, \nsemen, and vaginal fluid of an infected person. Saliva is also a body \nfluid but the virus concentration is 1,000 to 10,000 times less than \nwhat is found in the blood.\n\nYou may risk exposure to hepatitis B through unprotected sex, tattoos,\n piercings, pedicures, manicures or medical procedures with improperly \nsterilized equipment, sharing personal hygiene items with an infected \nperson (e.g. razors, toothbrushes, nail clippers) or providing emergency \nfirst aid in which you come in contact with blood or other body fluids.\n\n"));
           q.Add(new info(5, 0, "What are the symptoms B ?", "What happens to you when you contract hepatitis B depends largely on the \nage at which you first become infected and how well your immune system \ncopes with the virus. If you are infected as an adult, you may have a \nbrief illness with mild or moderate symptoms such as jaundice, dark \nurine, fatigue, abdominal discomfort, and loss of appetite.  As an \nadult, you have a 95% chance of clearing the infection completely and \ndeveloping lifelong protection against this virus. The acute infection \nrarely (in less than 1% of cases) leads to severe illness that requires \na liver transplant. \n\nMost babies and children exposed to this virus never have signs and \nsymptoms. Unfortunately, they are more likely to become carriers of \nhepatitis B for life because their immune system is unable to fight \nand clear the virus from their body.  In these cases, chronic \ninfections are often not detected or “picked up” until much later in \nlife when the person becomes seriously ill with liver disease.\n\nChronic hepatitis B infection goes through different phases that \nalso show how well your body is coping with the virus. Although most \npeople with chronic hepatitis B have inactive disease and will remain \nhealthy, about one in four will have active disease that may lead to \ncirrhosis (scarring of the liver), liver failure, and liver cancer.\n\nPeople who are healthy with inactive disease may still be at risk of \nvirus reactivation, especially when their immune system is weakened by \nmedicines such as chemotherapy or by other viral infections.\n\nYou will need treatment if you have ongoing active disease that causes \na lot of damage to your liver, or if you are going to take medicines \nthat will weaken your immune system.\n\n  "));
           q.Add(new info(6, 0, "What is hepatitis C?", "Hepatitis is a liver disease caused by the hepatitis C virus that \nattacks the liver. Many people who become infected with hepatitis \nC never feel sick and recover completely. Others get a brief, \nacute illness with fatigue and loss of appetite and their skin \nand eyes turn yellow (a condition called “jaundice”). If your body \nis not able to fight off the virus, you may develop chronic \nhepatitis which can lead to cirrhosis (liver scarring), liver \nfailure and even liver cancer later in life. Like chronic \nhepatitis B, chronic hepatitis C is a “silent” disease because \noften no symptoms appear until your liver is severely damaged.\n\n"));
           q.Add(new info(7, 0, "How do I get hepatitis C ?", "Hepatitis C is common worldwide.  An estimated 170 million individuals \nworldwide including an estimated 250,000 in Canada are infected. \nHepatitis C is spread through blood-to-blood contact, which means that \nto contract hepatitis C, blood infected with the hepatitis C virus must \nget into your blood stream\n\nYou may risk exposure to hepatitis C by using injection drugs (even once), \ngetting tattoos, piercings, pedicures, manicures or medical procedures \nwith improperly sterilized equipment, sharing personal hygiene items with \nan infected person (e.g. razors, toothbrushes, nail clippers) or having had \na blood transfusion or received blood products prior to July 1990. \n\n"));
           q.Add(new info(8, 0, "What are the symptoms C ?",  "When you have just become infected with the hepatitis C virus, you may \nhave no symptoms and may not even know you have been infected. This is \nthe acute infection phase and can last from six to eight weeks, or \nlonger. If you have symptoms, they are usually mild and may include \nfatigue, lethargy, nausea, reduced appetite, abdominal pain and jaundice.\n\nOver time, the virus may disappear on its own, and you are no longer \ninfected. This happens to approximately 25 out of 100 hepatitis \nC-infected people. If the virus does not disappear after six months,\nyour infection is chronic. This happens to approximately 75 out of 100 \nhepatitis C-infected people.\n\nIf your hepatitis C is chronic, in three out of four cases, you will\nhave only very mild to moderate damage to your liver over time.  \nHowever, in one out of four cases, chronic hepatitis C can lead to \nmore serious problems including cirrhosis, liver failure and liver \ncancer over a period of 25 to 30 years.\n\nYou are more likely to develop cirrhosis if you drink alcohol, are \nobese, are male, became infected after age 40, have another type of \nliver disease or have another chronic infection, such as HIV or \nhepatitis B in addition to hepatitis C.\n\n"));
           
       }


       public void heart()
       {
           q.Add(new info(1, 0, "What's Heart Disease ?", "Heart disease is a word used to describe many different conditions \naffecting the heart. Coronary heart disease is a common type of \nheart disease. This condition results from a buildup of plaque on \nthe inside of the arteries, which reduces blood flow to the heart \nand increases the risk of a heart attack and other heart \ncomplications. Other forms of heart disease include:\n\n    irregular heartbeat (arrhythmias)\n    congenital heart defects\n    weak heart muscles (cardiomyopathy)\n    heart valve problems\n    heart infections\n    cardiovascular disease\n\nApproximately 600,000 people die from heart disease in the United \nStates every year, according to the Centers for Disease and \nControl Prevention (CDC). It’s a leading cause of death in \nboth men and women\n\n"));
           q.Add(new info(1, 0, "Symptoms of Heart Disease ?!", "Heart disease is often called a “silent killer”. Your doctor may \nnot diagnose the disease until you show signs of a heart attack \nor heart failure. Symptoms of heart disease vary depending on \nthe specific condition. For example, if you have a heart \narrhythmia, symptoms may include:\n\n    a fast or slow heartbeat\n    dizziness\n    lightheadedness\n    chest pains\n    shortness of breath\n\nSymptoms of congenital heart defect may include skin \ndiscoloration, such as a bluish or pale color. You \nmay also notice swelling in your legs and stomach. \nYou might become easily tired or have shortness of \nbreath shortly after beginning any type of physical activity.\n\nIf you have weak heart muscles, physical activity may cause \ntiredness and shortness of breath. Dizziness and swelling in \nthe legs, ankle, or feet are also common with cardiomyopathy. \nSigns and symptoms of a heart infection can include:\n\n    tiredness\n    coughing\n    skin rash\n    irregular heartbeat\n    swelling in legs and stomach\n\nSeek medical attention if you have any signs of heart problem.\nIt’s important to address symptoms early since there are many \ntypes of heart diseases, each with its own set of symptoms.\n\n"));
           q.Add(new info(1, 0, "Risk Factors of Heart Disease", "Several factors increase your risk of heart disease, like a family \nhistory of the disease, age, or ethnicity. Other common risk factors \ninclude:\n\n    smoking\n    high blood pressure\n    high blood cholesterol\n    diabetes\n    poor diet\n    lack of exercise\n    obesity\n    stress\n    poor hygiene (some viral and bacterial infections can affect the heart)"));
           q.Add(new info(1, 0, "Diagnosing Heart Disease", "Different tests are used to diagnose heart disease, and your doctor \nmay choose a particular test based on your symptoms and a review of \nyour family history. After a blood test and chest X-ray, other \ntests include:\n\n    electrocardiogram (EKG): a test that helps doctors identify \n    problems with your heart’s rhythm\n\n    echocardiogram: a test that uses ultrasound waves to view the \n    flow of blood through the heart\n\n    cardiac computerized tomography (CT) scan: an X-ray test that \n    creates cross sectional views of your heart\n\n    cardiac magnetic resonance imaging (MRI): a test that uses \n    powerful magnets and radio waves to create images of your \n    heart and surrounding tissue\n\n    stress test: a test that monitors your heart during \n    periods of strenuous activity or exercise\n"));
           q.Add(new info(1, 0, "How to Treat Heart Disease ?", "Heart disease treatments depend on the condition, but may include \nlifestyle changes and medications. Lifestyle changes can include:\n\n    eating a healthy diet rich in fiber, omega-3 fatty acids, \n    fruits, and vegetables. Choose foods that are low in fat, \n    sodium, and cholesterol to help control your blood pressure.\n\n    increasing physical activity to maintain a healthy weight, \n    reduce your risk of diabetes, and improve cholesterol levels. \n\n    Aim for at least 60 minutes of activity per week, says the \n    National Heart, Lung and Blood Institute.\n\n    quitting smoking can lower your risk of heart disease \n    and complications.\n\n    drinking alcohol in moderation can lower blood pressure and \n    decrease the risk for heart disease. Men should drink no more \n    than two, and women no more than one alcoholic beverage per day, \n    according to the National Institute on Alcohol Abuse and Alcoholism.\n\n    learning how to deal with stress, either through exercise, \n    medication, stress management therapy or support groups\n\nWhen lifestyle changes do not improve your conditions, doctors may \nprescribe certain medications to reduce your risk of a heart attack \nor stroke. These include medications that lower blood pressure or \nprevent blood clotting.\n\nSometimes, medical procedures are necessary to treat certain types \nof heart disease. These include an angioplasty (a flexible tube i\nnserted in arteries to improve blood flow) or a coronary artery \nbypass surgery (blood vessels surgically moved from one area of \nthe body to another to improve blood flow to the heart).\n\n"));
           
       }


       public void hyper()
       {
           q.Add(new info(0, 0, "What Is High Blood Pressure? ", "High blood pressure, also known as hypertension, is the most \ncommon cardiovascular disease.\n\nBlood pressure refers to the force of blood pushing against \nartery walls as it courses through the body. Like air in a \ntire or water in a hose, blood fills arteries to a certain \ncapacity. Just as too much air pressure can damage a tire \nor too much water pushing through a garden hose can damage \nthe hose, high blood pressure can threaten healthy \narteries and lead to life-threatening conditions \nsuch as heart disease and stroke.\n\nHypertension is the leading cause of stroke and a major \ncause of heart attack. In the U.S. alone, more than \n30% of American adults have high blood pressure.\n\nIf you have high blood pressure, you'll probably find \nout about it during a routine checkup. Or, you may have \nnoticed a problem while taking your own blood pressure. \nBe sure to see your doctor for a definite diagnosis, \nand take the opportunity to learn what you can do to \nbring your blood pressure under control.\n\n"));
           q.Add(new info(1, 0, "How Is Blood Pressure Measured?", "A blood pressure reading appears as two numbers. The first and \nhigher of the two is a measure of systolic pressure, or the \npressure in the arteries when the heart beats and fills them \nwith blood. The second number measures diastolic pressure, or \nthe pressure in the arteries when the heart rests between beats.\n\nNormal blood pressure rises steadily from about 90/60 at birth \nto about 120/80 in a healthy adult. If someone were to take your \nblood pressure immediately after you'd delivered a speech or \njogged 5 miles, the reading would undoubtedly seem high. This \nis not necessarily cause for alarm: It's natural for blood \npressure to rise and fall with changes in activity \nor emotional state.\n\nIt's also normal for blood pressure to vary from person to \nperson, even from one area of the body to another. But when \nblood pressure remains consistently high, talk with your \ndoctor about treatment. Consistently high blood pressure \nforces the heart to work far beyond its capacity. Along \nwith injuring blood vessels, hypertension can damage \nthe brain, eyes, and kidneys. \n\n"));
           q.Add(new info(2, 0,"What Is Hypertension in Children?","Blood pressure is the force of blood as it flows through the body's\n vessels. Under normal conditions, the heart pumps blood through \nthe vessels all over the body. The vessels widen and contract as \nneeded to keep blood flowing well. In a person with hypertension, \nhowever, the blood pushes too hard against the blood vessels, which \ncan cause damage to blood vessels, the heart, and other organs.\n\nIt's easy for adults to tell if they have high blood pressure simply \nby having blood pressure checks and comparing the numbers to \na simple chart. Children have the same tests; however, interpreting \nthe numbers is trickier. Your child's doctor will use charts based \non your child's sex, height, and blood pressure numbers to \ndetermine whether or not your child has high blood pressure.\n\n"));
           q.Add(new info(3, 0, "What causes high blood pressure?", "Blood pressure is the measure of the force of blood \npushing against blood vessel walls. The heart pumps \nblood into the arteries (blood vessels), which carry \nthe blood throughout the body. High blood pressure, \nalso called hypertension, is dangerous because it \nmakes the heart work harder to pump blood to the \nbody and contributes to hardening of the arteries, \nor atherosclerosis, and to the development of heart failure."));
           q.Add(new info(4, 0,"What Is Normal Blood Pressure?","A blood pressure reading has a top number (systolic) \nand bottom number (diastolic). The ranges are:\n\n    Normal: Less than 120 over 80 (120/80)\n    Prehypertension: 120-139 over 80-89\n    Stage 1 high blood pressure: 140-159 over 90-99\n    Stage 2 high blood pressure: 160 and above over 100 and above\n    High blood pressure in people over age 60:150 & above over 90 \n\nPeople whose blood pressure is above the normal range\n should consult their doctor about steps to take to lower it.\n"));
    
           q.Add(new info(5, 0, "How Can I Prevent Hypertension ?", "- Maintaining a healthy weight\n- Getting regular exercise\n- Reducing salt intake\n- Reduce stress\n- Eating foods rich in potassium\n- A diet low in magnesium may make your blood pressure rise\n- fish oils may help reduce high blood pressure\n "));
       
       }

       public void diabetes()
       {
           q.Add(new info(0, 0, "What is diabetes?", "Diabetes is a disease of the pancreas, an organ located behind your\nstomach. Normally, the pancreas releases a substance called \ninsulin into the blood. Insulin helps the body to use sugars and \nfats that are broken down from the foods we eat. \nWhen a person has diabetes, the pancreas:\n\n    -Does not make insulin\n    -Makes only a little insulin or,\n    -Makes insulin, but the insulin does not work as it should.\n\nDiabetes is a lifelong disease.\nPeople with diabetes must manage their disease to stay healthy."));
           q.Add(new info(1, 0, "What causes diabetes?", "Health care providers do not yet know what causes diabetes.\nThe following factors may increase your chance of getting diabetes:\n\n    -Family history of diabetes\n    -Being overweight\n    -Age (Chances increase with age)\n    -Taking certain medicines\n    -Being pregnant*\n\n*Pregnancy puts extra stress on a woman's body that causes\nsome women to develop diabetes. Blood sugar levels often \nreturn to normal after childbirth. Yet, women who get \ndiabetes during pregnancy have an increased chance of \ndeveloping diabetes later in life.\n\n"));
           q.Add(new info(2, 0, "What are the types of diabetes?", "There are two types of diabetes: type 1 and type 2.\n\n    -Type 1 diabetes — The pancreas makes little or \n     no insulin. A person with type 1 diabetes must \n     take insulin to survive. This type occurs most \n     often in people who are under 30 years old.\n\n\n    -Type 2 diabetes — Insulin is made but it doesn't \n     work as it should. Nine out of 10 people with diabetes \n     have type 2 diabetes. This type occurs most often in \n     people who are over 40 years old and overweight.\n")) ;
           q.Add(new info(3, 0, "What are the diabetes symptoms?", "Type 1 diabetes\n    -Increased thirst\n    -Dry mouth\n    -A need to urinate often\n    -Weight loss (even though you are eating and feel hungry)\n    -Weak, tired feeling\n    -Blurred vision\n\nType 2 diabetes\n    -Blurred vision\n    -Slow healing sores or cuts\n    -Itchy skin (usually in the vaginal or groin area)\n    -Yeast infections\n    -Increased thirst\n    -Dry mouth\n    -A need to urinate often\n"));
           q.Add(new info(4, 0, "Is there a treatment for diabetes?", "No. A cure for diabetes has not yet been found. However, diabetes\ncan be treated and controlled. Most people with diabetes manage \ntheir disease and lead normal lives. Without proper care, \ndiabetes can lead to:\n\n    -Heart disease\n    -Kidney disease\n    -High blood pressure\n    -Low blood pressure\n    -Eye damage and blindness\n    -Gum disease\n    -Serious infections in feet, sometimes requiring amputation\n    -Damage to nerves, resulting in pain or loss of sensation"));
       }




   }






}
