using System;
using System.Collections.Generic;
using System.Text;

namespace intro
{
   public class Medicines
    {
       public int id { set; get; }
        public int type { set; get; }
        public string name { set; get; }
        public string img { set; get; }
        public string side_effects { set; get; }

        public Medicines(int _id, int _type , string _name ,  string _img , string _side_effets)
        {
            id = _id;
            type = _type;
            name = _name;
            img = _img;
            side_effects = _side_effets;
            

        }
        
    }


   public class Medicines_fill
    {
       public List<Medicines> med = new List<Medicines>();

       public void liver()
       {
           med.Add(new Medicines(0, 0, " sovaldi", "/Assets/liver/solvadi.jpg",            "Sovaldi (sofosbuvir) is an antiviral medication that \nprevents hepatitis C virus (HCV) cells from \nmultiplying in your body. If any of the following \nside effects occur while taking sofosbuvir, check \nwith your doctor immediately:\n\nMore common\n    chills\n    fever\n    lower back or side pain\n    pale skin\n    ulcers, sores, or white spots in the mouth\n    unusual tiredness or weakness\n\nRare\n    Changes in behavior\n    discouragement\n    feeling sad or empty\n    loss of interest or pleasure\n    thoughts of killing oneself\n    trouble concentrating"));
           med.Add(new Medicines(1, 0, " Olysio (simeprevir)", "/Assets/liver/Olysio.jpg", "Victrelis (boceprevir) is an antiviral medication \nthat prevents certain virus cells from multiplying \nin your body If any of the following side \neffects occur while taking boceprevir, check \nwith your doctor immediately:\n\nMore common\n    Black, tarry stools\n    chills\n    cough\n    difficult or labored breathing\n    fever\n    lower back or side pain\n    painful or difficult urination\n    pale skin\n    sore throat\n    tightness in the chest\n    troubled breathing with exertion\n    ulcers, sores, or white spots in the mouth\n    unusual bleeding or bruising\n    unusual tiredness or weakness\n"));
           med.Add(new Medicines(2, 0, " BayGam ", "/Assets/liver/BayGam.JPG",             "BayGam is used for: Providing antibodies to help \nprevent infection in certain patients who have \na weakened immune system, or who have been \nexposed to measles, hepatitis A, or chickenpox. \nIt may also be used for other conditions as \ndetermined by your doctor Check with your \ndoctor if any of these most COMMON side \neffects persist or become bothersome:  Pain, \nswelling, tenderness, or redness at the \ninjection site. Seek medical attention right \naway if any of these SEVERE side effects occur \nwhile taking immune globulin intramuscular \n(the active ingredient contained in BayGam) \nSevere allergic reactions (rash; itching; \nhives; difficulty breathing or swallowing; \ntightness in the chest; swelling of the mouth, \nhands, face, lips, eyes, throat, or tongue) "));
           med.Add(new Medicines(3, 0, " GamaSTAN S/D", "/Assets/liver/GamaSTAN SD.jpg", "GamaSTAN is used for:Providing antibodies to help prevent \ninfection in certain patients who have a weakened immune \nsystem, or who have been exposed to measles, hepatitis A, \nor chickenpox. It may also be used for other conditions \nas determined by your doctor\n\nCheck with your doctor if any of these most COMMON side \neffects persist or become bothersome:\n\nPain, swelling, tenderness, or redness at the injection site.\n\nSeek medical attention right away if any of these SEVERE \nside effects occur while taking immune globulin intramuscular \n(the active ingredient contained in GamaSTAN S / D)\n\nSevere allergic reactions (rash; itching; hives; difficulty \nbreathing or swallowing; tightness in the chest; swelling of \nthe mouth, hands, face, lips, eyes, throat, or tongue).\n\n"));
           med.Add(new Medicines(4, 0, " Biogam", "/Assets/liver/Biogam.jpg",             "Check with your doctor if any of these most \nCOMMON side effects persist or become \nbothersome:    Pain, swelling, tenderness, or \nredness at the injection site. \n\nSeek medical attention right away if any of these \nSEVERE side effects occur while taking immune \nglobulin intramuscular (the active ingredient \ncontained in Biogam)Severe allergic reactions \n(rash; itching; hives; difficulty breathing or \nswallowing; tightness in the chest; swelling of \nthe mouth, hands, face, lips, eyes, throat, \nor tongue)"));
           med.Add(new Medicines(5, 0, " Epivir-HBV", "/Assets/liver/Epivir-HBV.jpg",     "Epivir-HBVTreating certain types of chronic hepatitis B virus \n(HBV) infection.\nYou should check with your doctor immediately if any of \nthese side effects occur when taking lamivudine:\n\nIncidence not known \n    Abdominal or stomach discomfort\n    black, tarry stools\n    bleeding gums\n    bloating\n    blood in the urine or stools\n    chills\n    constipation\n    cough\n    darkened urine\n    decreased appetite\n    diarrhea\n    difficulty swallowing\n    dizziness\n    fast heartbeat\n    fast, shallow breathing\n    fever\n    general feeling of discomfort\n    general tiredness and weakness\n    indigestion\n    light-colored stools\n    loss of appetite\n    muscle cramps or spasms\n    muscle pain or stiffness\n    nausea and vomiting\n    pains in the stomach, side, or abdomen\n    pinpoint red spots on the skin\n    right upper abdominal or stomach pain and fullness\n    skin rash, hives, or itching\n    sleepiness\n    tightness in the chest\n    unusual bleeding or bruisin\n    unusual tiredness or weakness\n    upper right abdominal or stomach pain\n    yellow eyes or skin"));
           med.Add(new Medicines(6, 0, " Baraclude", "/Assets/liver/Baraclude.jpg", "You should check with your doctor immediately if any of \nthese side effects occur when taking entecavir:\n\nIncidence not known\n      Abdominal or stomach discomfort\n      cough\n      decreased appetite\n      diarrhea\n      difficulty with swallowing\n      dizziness\n      fast heartbeat\n      fast, shallow breathing\n      general feeling of discomfort\n      hives, itching, or rash\n      muscle pain or cramping\n      nausea\n      puffiness or swelling of the eyelids\n      right upper abdominal or stomach pain\n      sleepiness\n      tightness in the chest\n      unusual tiredness or weakness\n\nLess common\n      Acid or sour stomach\n      belching\n      headache\n      heartburn\n      indigestion\n      stomach discomfort, upset, or pain"));
           med.Add(new Medicines(7, 0, " Hepsera", "/Assets/liver/Hepsera.jpg", "Not all side effects for Hepsera may be reported. You \nshould always consult a doctor or healthcare professional\nfor medical advice. Side effects can be reported \nto the FDA here.\n\nApplies to adefovir: oral tablets\n      Asthenia\n      headache\n      abdominal pain\n      nausea\n      flatulence\n      diarrhea\n      dyspepsia"));
           med.Add(new Medicines(8, 0, " Viread", "/Assets/liver/Viread.JPG", "As well as its needed effects, tenofovir (the active \ningredient contained in Viread) may cause unwanted side \neffects that require medical attention.\nIf any of the following side effects occur while taking\ntenofovir, check with your doctor immediately:\n\nLess common\n    Chest pain\n    cough\n    fever or chills\n    tightness in the chest\n    troubled breathing\n\nRare\n    Abdominal or stomach discomfort\n    decreased appetite\n    diarrhea\n    fast, shallow breathing\n    general feeling of discomfort\n    muscle pain or cramping\n    unusual tiredness or weakness"));


       }

       public void Heart()
       {
           med.Add(new Medicines(0, 1, "Penicillin", "/Assets/heart/penicillin.jpg", "Stop taking penicillin and get emergency help \nimmediately if any of the following effects occur:\n\nLess common\n    Fast or irregular breathing\n    fever\n    joint pain\n    lightheadedness or fainting (sudden)\n    puffiness or swelling around the face\n    red, scaly skin\n    shortness of breath\n    skin rash, hives, itching\nIf any of the following side effects occur while \ntaking penicillin, check with your doctor immediately:\n\nRare\n    Abdominal or stomach cramps and pain (severe)\n    abdominal tenderness\n    convulsions (seizures)\n    decreased amount of urine\n    diarrhea (watery and severe), which may also be bloody\n    mental depression\n    nausea and vomiting\n    pain at place of injection\n    sore throat and fever\n    unusual bleeding or bruising\n    yellow eyes or skin\n\n"));
           med.Add(new Medicines(1, 1, "Spironolactone ", "/Assets/heart/Spironolactone.jpg", "Spironolactone is used to treat high blood pressure. \nLowering high blood pressure helps prevent strokes, \nheart attacks, and kidney problems.\n\nDrowsiness, dizziness, lightheadedness, stomach upset, \ndiarrhea, nausea, vomiting, or headache may occur. To \nminimize lightheadedness, get up slowly when rising \nfrom a seated or lying position. If any of these effects \npersist or worsen, notify your doctor or pharmacist promptly.\n\nRemember that your doctor has prescribed this medication \nbecause he or she has judged that the benefit to you is \ngreater than the risk of side effects. Many people using \nthis medication do not have serious side effects.\n\nTell your doctor immediately if any of these unlikely but \nserious side effects occur: increased thirst, change in \nthe amount of urine, mental/mood changes, unusual \nfatigue/weakness, muscle spasms, menstrual period changes, \nbreast pain, breast enlargement (gynecomastia) in men, \nsexual function problems...\n\n"));
           med.Add(new Medicines(2, 1, "LANOXIN 62.5", "/Assets/heart/LANOXIN.jpg", "LANOXIN 62.5 MCG TABLET (Digoxin) is used to treat \nheart failure, usually along with other medications. \nIt is also used to treat a certain type of irregular \nheartbeat (chronic atrial fibrillation).\n\nNausea, vomiting, headache, loss of appetite, \nand diarrhea may occur. If any of these effects persist \nor worsen, tell your doctor or pharmacist promptly.\n\nRemember that your doctor has prescribed this medication \nbecause he or she has judged that the benefit to you is \ngreater than the risk of side effects. Many people \nusing this medication do not have serious side effects.\n\nTell your doctor immediately if any of these unlikely \nbut serious side effects occur: weakness, mental/mood \nchanges, vision changes (such as blurred or \nyellow/green vision), enlarged/tender breasts in men.\n\nThough this medication is used to treat a certain type \nof irregular heartbeat, it may infrequently cause other \ntypes of irregular heartbeats. Tell your doctor \nimmediately if you notice any unusually \nfast/slow/irregular heartbeat\n\n"));
           med.Add(new Medicines(3, 1, "Warfarin", "/Assets/heart/warfarin.jpg", "This medication is used to treat blood clots(such as in \ndeep vein thrombosis-DVT or pulmonary embolus-PE) and/or \nto prevent new clots from forming in your body\n\nNausea, loss of appetite, or stomach/abdominal pain may \noccur. If any of these effects persist or worsen, tell \nyour doctor or pharmacist promptly.\n\nRemember that your doctor has prescribed this medication \nbecause he or she has judged that the benefit to you is \ngreater than the risk of side effects. Many people using \nthis medication do not have serious side effects.\n\nThis medication can cause serious bleeding if it affects \nyour blood clotting proteins too much (shown by unusually \nhigh INR lab results). Even if your doctor stops your \nmedication, this risk of bleeding can continue for up to \na week. Tell your doctor right away if you have any signs \nof serious bleeding, including: unusual pain/swelling/\ndiscomfort, unusual/easy bruising, prolonged bleeding \nfrom cuts or gums, persistent/frequent nosebleeds, \nunusually heavy/prolonged menstrual flow, pink/dark urine, \ncoughing up blood, vomit that is bloody or looks like coffee \ngrounds, severe headache, dizziness/fainting, unusual or \npersistent tiredness/weakness, bloody/black/tarry stools, \nchest pain, shortness of breath, difficulty swallowing.\n\n"));
           med.Add(new Medicines(4, 1, "Lipitor", "/Assets/heart/Lipitor.jpg", "Lipitor is used to treat high cholesterol, and to lower \nthe risk of stroke, heart attack, or other heart \ncomplications in people with type 2 diabetes, coronary \nheart disease, or other risk factors\n\nRemember that your doctor has prescribed this medication \nbecause he or she has judged that the benefit to \nyou is greater than the risk of side effects. Many \npeople using this medication do not have serious side effects.\n\nA very small number of people taking atorvastatin may \nhave mild memory problems or confusion. If these rare \neffects occur, talk to your doctor.\n\nRarely, statins may cause or worsen diabetes. Talk to \nyour doctor about the benefits and risks.\n\nThis drug may infrequently cause muscle problems (which \ncan rarely lead to very serious conditions called \nrhabdomyolysis and autoimmune myopathy). Tell your \ndoctor right away if you develop any of these symptoms during \ntreatment and if these symptoms persist after your doctor \nstops this drug: muscle pain/tenderness/weakness \n(especially with fever or unusual tiredness), \nchange in the amount of urine.\n\nThis medication may rarely cause liver problems. If you \nnotice any of the following rare but serious side \neffects, tell your doctor immediately: yellowing \neyes/skin, dark urine, severe stomach/abdominal pain, \npersistent nausea/vomiting.\n\nA very serious allergic reaction to this drug is rare. \nHowever, seek immediate medical attention if you notice \nany symptoms of a serious allergic reaction, \nincluding: rash, itching/swelling (especially of the face/tongue/throat), \nsevere dizziness, trouble breathing.\n\n"));
           med.Add(new Medicines(5, 1, "Zocor ", "/Assets/heart/Zocor.jpg", "Simvastatin (Zocor)is used along with a proper diet to \nhelp lower  cholesterol and fats (such as LDL, \ntriglycerides) and raise cholesterol (HDL) in \nthe blood. It belongs to a group of drugs known as \n It works by reducing the amount of cholesterol \nmade by the liver. Lowering  cholesterol and \ntriglycerides and raising  cholesterol decreases \nthe risk of heart disease and helps prevent strokes and \nheart attacks\n\nA very small number of people taking simvastatin may\n have mild memory problems or confusion. If these rare \neffects occur, talk to your doctor.\n\nRarely, statins may cause or worsen diabetes. Talk \nto your doctor about the benefits and risks.\n\nThis drug may infrequently cause muscle problems \n(which can rarely lead to very serious conditions called \nrhabdomyolysis and autoimmune myopathy). Tell your \ndoctor right away if you develop any of these \nsymptoms during treatment and if these symptoms persist \n after your doctor stops this drug: muscle pain/weakness \n(especially with fever or unusual tiredness), \nchange in the amount of urine.\n\nThis medication may rarely cause liver problems.\n If you notice any of the following rare but serious \nside effects, tell your doctor immediately: \nyellowing eyes/skin, dark urine, severe stomach/abdominal \npain, persistent nausea/vomiting.\n\n"));

       }



       public void hyper()
       {
           med.Add(new Medicines(0, 2, " Diltiazem", "/Assets/hyper/Diltiazem.jpg", "Diltiazem is used to treat hypertension (high blood \npressure), angina (chest pain), and certain heart \nrhythm disorders\n\nYou should check with your doctor immediately if any \nof these side effects occur when taking diltiazem:\n\nMore common\n    Body aches or pain\n    congestion\n    cough\n    dryness or soreness of throat\n    fever\n    hoarseness\n    runny nose\n    tender or swollen glands in neck\n    trouble in swallowing\n    voice changes\n\nLess common\n    Chest pain or discomfort\n    chills\n    diarrhea\n    difficult or labored breathing\n    feeling faint, dizzy, or lightheaded\n    feeling of warmth or heat\n    flushing or redness of skin, especially on face and neck\n    general feeling of discomfort or illness\n    headache\n    joint pain\n    loss of appetite\n    muscle aches and pains\n    nausea\n    shivering\n    shortness of breath\n    slow or irregular heartbeat\n    sore throat\n    sweating\n    swelling of hands, ankles, feet, or lower legs\n    tightness in chest\n    trouble sleeping\n    unusual tiredness or weakness\n    vomiting\n    wheezing\n\n"));
           med.Add(new Medicines(1, 2, " hydrochlorothiazide", "/Assets/hyper/hydrochlorothiazide.jpg", "HCTZ treats fluid retention (edema) in people with \ncongestive heart failure, cirrhosis of the liver, or \nkidney disorders, or edema caused by taking steroids \nor estrogen. This medication is also used to treat \nhigh blood pressure (hypertension)\n\nYou should check with your doctor immediately if any of \nthese side effects occur when taking hydrochlorothiazide:\n\nIncidence not known\n    Abdominal or stomach pain\n    back, leg, or stomach pains\n    black, tarry stools\n    bleeding gums\n    blistering, peeling, or loosening of the skin\n    blood in the urine or stools\n    blue lips and fingernails\n    blurred vision\n    burning, crawling, itching, numbness, prickling,\n    chest pain\n    chills\n    cloudy urine\n    cold sweats\n    confusion\n    constipation\n    cough or hoarseness\n    coughing that sometimes produces a pink frothy sputum\n    coughing up blood\n    cracks in the skin\n    darkened urine\n    decrease in urine output or \n    decreased frequency or amount of urine\n    diarrhea\n    difficult, fast, or noisy breathing\n    difficulty with breathing\n    difficulty with swallowing\n    lightheadedness when getting up from a lying \n    dry mouth\n    fast or irregular heartbeat\n    fever\n    flushed, dry skin\n    fruit-like breath odor\n    general body swellin\n    general feeling of discomfort or illness\n    headache\n    hives\n    increased blood pressure\n    increased hunger\n    increased sweating\n    yellow eyes or skin\n     thirst\n    pale skin\n    muscle cramps or pain\n\n"));
           med.Add(new Medicines(2, 2, " Atenolol ", "/Assets/hyper/Atenolol.jpg", "Atenolol is used to treat angina (chest pain) and \nhypertension (high blood pressure). It is also used \nto treat or prevent heart attack.\n\nMore common\n    Blurred vision\n    cold hands or feet\n    confusion\n    difficult or labored breathing\n    lightheadedness when getting up from a lying or sitting\n    shortness of breath\n    sweating\n    tightness in chest\n    unusual tiredness or weakness\n    wheezing\n\nLess common\n    Anxiety\n    chest pain or discomfort\n    chills\n    cold sweats\n    cough\n    dizziness or lightheadedness\n    fainting\n    fast heartbeat\n    leg pain\n    noisy breathing\n    slow or irregular heartbeat\n    sudden shortness of breath or troubled breathing\n\nRare\n    Bloody urine\n    decreased frequency or amount of urine\n    increased blood pressure\n    increased thirst\n    loss of appetite\n    lower back or side pain\n    nausea\n    swelling of face, fingers, or lower legs\n    vomiting\n    weight gain\n\n"));
           med.Add(new Medicines(3, 2, " Amiloride ", "/Assets/hyper/Amiloride.jpg", "Amiloride is used to treat or prevent hypokalemia \n(low potassium levels in the blood)\n\nMore common\n    Abdominal pain\n    confusion\n    difficulty with breathing\n    irregular heartbeat\n    nausea or vomiting\n    nervousness\n    numbness or tingling in the hands, feet, or lips\n    shortness of breath\n    weakness or heaviness of the legs\n\nLess common\n    Agitation\n    back pain\n    blurred vision\n    coma\n    dizziness\n    drowsiness\n    fever\n    hallucinations (seeing things that aren't there)\n    headache\n    irritability\n    labored breathing\n    mood or mental changes\n    seizures (convulsions)\n    stiff neck\n    tightness in the chest\n    unusual tiredness or weakness\n    vomiting\n    wheezing\n\n"));
           med.Add(new Medicines(4, 2, " Isradipine ", "/Assets/hyper/Isradipine.jpg", "Isradipine is used to treat high blood pressure \n(hypertension). It is sometimes given with other \nblood pressure medications.\n\nMore common\n    Bloating or swelling of face, arms, hands, legs,\n    tingling of hands or feet\n    unusual weight gain or loss\n\nLess common\n    Chest pain\n    difficult or labored breathing\n    dizziness\n    fast, irregular, pounding, or racing heartbeat or pulse\n    feeling of warmth\n    full or bloated feeling\n    nausea\n    pressure in the stomach\n    redness of the face, neck, arms and occasionally, \n    shortness of breath\n    swelling of abdominal or stomach area\n    tightness in chest\n    unusual tiredness or weakness\n    vomiting\n    wheezing\n\n"));
           med.Add(new Medicines(5, 2, " Eplerenone ", "/Assets/hyper/Eplerenone.jpg", "Eplerenone is used to treat congestive heart failure \nafter a heart attack. Eplerenone is also used \nto treat high blood pressure (hypertension)\n\nLess common\n    Excess of cholesterol in the blood\n    excess of triglycerides in the blood\n\nIncidence not known\n    Abdominal or stomach pain\n    arm, back, or jaw pain\n    chest pain or discomfort\n    chest tightness or heaviness\n    confusion\n    difficulty with breathing\n    dizziness\n    fast or irregular heartbeat\n    headache\n    irregular heartbeat\n    large, hive-like swelling on the face, eyelids, lips,\n    nausea\n    nervousness\n    numbness or tingling in the hands, feet, or lips\n    pain or discomfort in the arms, jaw, back, or neck\n    rash\n    shortness of breath\n    sweating\n    vomiting\n    weakness or heaviness of the legs\n\n"));
       }

       public void diabtese()
       {
           med.Add(new Medicines(0, 3, " Apidra ", "/Assets/diabetes/Apidra.jpg", "Apidra is an inhection that contains insulin glulisine. \nInsulin is a hormone that works by lowering \nlevels of glucose (sugar) in the blood. \nInsulin glulisine is a faster-acting form of insulin than \nregular human insulin.\n\nApidra is used to treat diabetes in adults and children \nwho are at least 4 years old. Apidra is usually given \ntogether with a long-acting insulin.\n\nYou should check with your doctor immediately if any of \nthese side effects occur when taking insulin glulisine:\n\nMore common\n    Anxiety\n    blurred vision\n    body aches or pain\n    chills\n    cold sweats\n    confusion\n    convulsions\n    cool, pale skin\n    cough\n    depression\n    difficulty with breathing\n    dizziness\n    ear congestion\n    fast heartbeat\n    headache\n    increased hunger\n    loss of voice\n    nasal congestion\n    nightmares\n    runny nose\n    shakiness\n    slurred speech\n    sneezing\n    sore throat\n    unconsciousness\n    unusual tiredness or weakness\n\nLess common\n    Pounding in the ears\n    slow or fast heartbeat\n\n"));
           med.Add(new Medicines(0, 3, " Humalog  ", "/Assets/diabetes/Humalog.jpg", "Humalog is used to treat type 1 (insulin-dependent) \ndiabetes in adults. It is usually given together \nwith another long-acting insulin.\n\n You should check with your doctor immediately if any of \nthese side effects occur when taking insulin lispro:\n\nMore common\n    Anxious or nervous feeling\n    behavior change similar to being drunk\n    blurred vision\n    cold sweats\n    confusion or difficulty thinking\n    convulsions (seizures)\n    depression\n    dizziness or lightheadedness\n    drowsiness\n    excessive hunger\n    fast heartbeat\n    fever or chills\n    headache\n    irritability or abnormal behavior\n    lower back or side pain\n    nightmares\n    painful or difficult urination\n    restless sleep\n    shakiness\n    slurred speech\n    tingling in the hands, feet, lips, or tongue\n    unconsciousness\n\nLess common\n    Dry, red, hot, or irritated skin\n\n"));
           med.Add(new Medicines(0, 3, " NovoLog  ", "/Assets/diabetes/NovoLog.jpg", "NovoLog (insulin aspart) is a fast-acting form of \ninsulin that works by lowering levels of glucose \n(sugar) in the blood.\n\nNovoLog is used to treat type 1 (insulin-dependent) \ndiabetes in adults and children who are at least \n2 years old. NovoLog is usually given together \nwith another long-acting insulin\n\nIf any of the following side effects occur while taking \ninsulin aspart, check with your doctor immediately:\n\nMore common\n    Anxious feeling\n    behavior change similar to being drunk\n    blurred vision\n    cold sweats\n    confusion\n    convulsions (seizures)\n    depression\n    difficulty with thinking\n    dizziness or lightheadedness\n    drowsiness\n    excessive hunger\n    fast heartbeat\n    headache\n    irritability or abnormal behavior\n    nightmares\n    restless sleep\n    shakiness\n    slurred speech\n    tingling in the hands, feet, lips, or tongue\n    unconsciousness\n\nLess common or rare\n    Depression of the skin at the place of injection\n    dryness of the mouth\n    fast or weak pulse\n    feeling of pressure, itching, redness\n    soreness, stinging, swelling, \n    or tingling at the place of injection\n    increased thirst\n    irregular heartbeat\n    loss of appetite\n    mood or mental changes\n    muscle cramps or pain\n    nausea or vomiting\n    shortness of breath\n\n"));
           
       }

       


    }




}
